- name: variables
  hosts: local
  connection: local
  vars:
    COURSE: "DevOps with aws"
    DURATION: 120HRS
    TRAINER: sivakumar
  tasks:
  - name: print the variable
    vars:
      COURSE: ansible
    ansible.builtin.debug:
      msg: "Course is {{COURSE}}, Duration is {{DURATION}},Trainer is {{TRAINER}}"

  - name: print the variable
    ansible.builtin.debug:
      msg: "Course is {{COURSE}}, Duration is {{DURATION}},Trainer is {{TRAINER}}"