- name: variables
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: please enter course name
    private: false
  - name: DURATION
    prompt: please enter course Duration 
    private: false
  - name: TRAINER
    prompt: please enter Trainer name
    private: false
  tasks:
  - name: print the variable
    ansible.builtin.debug:
      msg: "Course is {{COURSE}}, Duration is {{DURATION}},Trainer is {{TRAINER}}"
