- name: variables
  hosts: local
  connection: local
  vars:    #PLAY level variables
    GREET: "PLAY"
  vars_files:
  - course.yaml
  vars_prompt:
  - name: GREET
    prompt: Enter the values
    private: false
  
  tasks:
  - name: print the variable
    vars:
      GRRET: "TASK"
    ansible.builtin.debug:
      msg: "Hello from {{GREET}}"

# command line
# task level   
#prompt
#play 
#inventory
