- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefine variable
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Ramesh') }}"

  - name: convert string to list
    vars:
      fruits: "apple, banana, orange"
    ansible.builtin.debug:  
      msg: "fruits are: {{ fruits | split(',') }}"

  - name: convert map into list
    vars:
      course:
         name: ansible
         duration: 10hrs
         trainer: sivakumar
    ansible.builtin.debug:
      msg: "course info: {{ course | dict2items }}" 

  - name: convert list into map
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10hrs'}
      - {'key': 'trainer', 'value': 'sivakumar'}
    ansible.builtin.debug:
      msg: "course info: {{ course | items2dict }}"

  - name: convert upper tp lower
    vars:
      name: "sivakumar"
    ansible.builtin.debug:
      msg: "Hello {{ name | lower }}"

  - name: convert lower to upper
    vars:
      name: "sivakumar"
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}"

  - name: print min and max
    vars:  
      numbers: [1,30,57,87,98,24567]
    ansible.builtin.debug:
      msg: "Min is: {{ numbers | min }} Max is: {{ numbers | max }}"                              

    